# Generated by Django 5.0.6 on 2024-07-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='film',
            name='special_features',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
